###LOCALHOST REQUEST
###
GET http://localhost:8080/todos
###CREAT CONTACT (POST)
POST  http://localhost:8080/todos HTTP/1.1
content-type: application/json

{
    "todaysDate": "02/02/2023",
    "task": "get Project 2 running on Render",
    "dueDate": "02/03/2023",
    "class": "CSE341",
    "appointment": "none",
    "activities": "none",
    "notes": "wrk wrk wrk"
}
###UPDATE CONTACT (PUT)
PUT  http://localhost:8080/63dc70de6d0a4cd2630ecbe9 HTTP/1.1
content-type: application/json

{
    "todaysDate": "02/02/2023",
    "task": "get Project 2 running on MongoDB",
    "dueDate": "02/03/2023",
    "class": "CSE341",
    "appointment": "none",
    "activities": "none",
    "notes": "rest update"
}
###DELETE CONTACT (DELETE)
DELETE   http://localhost:8080/63dc70de6d0a4cd2630ecbeb HTTP/1.1
content-type: application/json
###




###RENDER REQUEST
###
GET https://cse341-project2-k61i.onrender.com/todos
###
###CREAT CONTACT (POST)
POST  https://cse341-project2-k61i.onrender.com/todos HTTP/1.1
content-type: application/json

{
    "todaysDate": "02/02/2023",
    "task": "get Project 2 running on Render",
    "dueDate": "02/03/2023",
    "class": "CSE341",
    "appointment": "none",
    "activities": "none",
    "notes": "wrk wrk wrk"
}
###UPDATE CONTACT (PUT)
PUT  https://cse341-project2-k61i.onrender.com/todos/63dc70de6d0a4cd2630ecbe9 HTTP/1.1
content-type: application/json

{
    "todaysDate": "02/02/2023",
    "task": "get Project 2 running on MongoDB",
    "dueDate": "02/03/2023",
    "class": "CSE341",
    "appointment": "none",
    "activities": "none",
    "notes": "rest update"
}
###DELETE CONTACT (DELETE)
DELETE   https://cse341-project2-k61i.onrender.com/todos/63dc8dd63f81ea9ed654ab21 HTTP/1.1